version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: merq_derja_viz
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 4000:3000
    environment:
      MB_DB_FILE: metabase.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      #MB_DB_USER_FILE: /run/secrets/db_user
      #MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_HOST: postgres
    networks:
      - metanet1
    #secrets:
     # - db_password
      #- db_user
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: merq_dereja_postgres
    hostname: postgres
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      #POSTGRES_USER_FILE: /run/secrets/db_user
      #POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - metanet1
 #   secrets:
  #    - db_password
   #   - db_user
networks:
  metanet1:
    driver: bridge
#secrets:
 #  db_password:
  #   file: db_password.txt
   #db_user:
    # file: db_user.txt