version: '3.9'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: merq_derja_viz
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 4000:3000
    environment:
      MB_DB_FILE: merqdereja.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: merqderejadb
      MB_DB_PORT: 5432
      MB_DB_USER: merqderejadb
      MB_DB_PASS: merqderejadb
      MB_DB_HOST: postgres
    networks:
      - merqderejadevnet

  postgres:
    image: postgres:latest
    container_name: merq_dereja_postgres
    hostname: postgres
    environment:
      POSTGRES_DB: merqderejadb
      POSTGRES_USER: merqderejadb
      POSTGRES_PASSWORD: merqderejadb
    networks:
      - merqderejadevnet

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: merqderejadev
      MYSQL_ROOT_PASSWORD: merqderejadmin
      MYSQL_USER: merqderejadev
      MYSQL_PASSWORD: merqderejadev
    networks:
      - merqderejadevnet

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3307:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=merqderejadev
      - PMA_PASSWORD=merqderejadev
    networks:
      - merqderejadevnet

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5434:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@merqconsultancy.org
      - PGADMIN_DEFAULT_PASSWORD=merqderejadev
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - merqderejadevnet

networks:
  merqderejadevnet:
