version: '3.8'

services:
  chat:
    image: derejame_chatbot  # Specify the Docker image name
    container_name: DerejaME_ChatBot  # Specify the Docker container name
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "8502:8502"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8502/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./chat:/chat
    environment:
      - PYTHONUNBUFFERED=1
