name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker-compose build

  deploy:
    name: Deploy Docker Container
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker-compose push

      # UnComment out the following step to deploy automatically to your server
      #- name: SSH into Server and Pull Docker Image
      #  uses: appleboy/ssh-action@master
      #  with:
      #    host: ${{ secrets.SERVER_HOST }}
      #    username: ${{ secrets.SERVER_USERNAME }}
      #    key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      #    script: |
      #      cd /path/to/project
      #      docker-compose pull
      #      docker-compose up -d
